using Task;
using System.Text;
Console.InputEncoding = Encoding.Unicode;
Console.OutputEncoding = Encoding.Unicode;
int rows;
int columns;
Console.WriteLine("Введіть кількість елементів масиву: ");
Console.WriteLine("Кількість рядків ");
rows = int.Parse(Console.ReadLine());
Console.WriteLine("Кількість стовпців ");
columns = int.Parse(Console.ReadLine());
int[,] matr = Matrix.GenerateMatrix(rows, columns);
MatrixConsole.PrintMatrix(matr);
int count = Matrix.CountPositiv(matr);
MatrixConsole.PrintCount(count);
int max = Matrix.MaxNumber(matr);
MatrixConsole.PrintMax(max);
int rowsZero = Matrix.RowsWithoutZero(matr);
MatrixConsole.PrintRowsWithoutZero(rowsZero);
int cols = Matrix.ColumnWithZero(matr); 
MatrixConsole.PrintColsWithZero(cols);
int longest = Matrix.RowWithLongestSeries(matr); 
MatrixConsole.PrintRowWithLongestSerie(longest);
int[] product = Matrix.ProductPositiv(matr);
MatrixConsole.PrintProduct(product);
int maxSum = Matrix.MaxSum(matr); 
MatrixConsole.PrintMaxSum(maxSum);
int[] sum = Matrix.SumPositiv(matr);
MatrixConsole.PrintSumCols(sum);
int minSum = Matrix.MinSum(matr);  
MatrixConsole.PrintMinSum(minSum);
int[] sumCols = Matrix.SumCols(matr);
MatrixConsole.PrintSumColsNeg(sumCols);
int[,] transposeMatr = Matrix.TransposeMatrix(matr);
MatrixConsole.PrintTransposeMatrix(transposeMatr);